### ISSUE TITLE
Issue extracting nvidia runtime libraries

### ISSUE THREAD

**Issue by lephino** [K4L0dev/Synology_Archive_Extractor#2]
I'm getting errno24 when trying to extract: NVIDIARuntimeLibrary-dva3221-1.0.2-0103.spk

It will extract the INFO file and then fails.  To recreate:

wget https://raw.githubusercontent.com/K4L0dev/Synology_Archive_Extractor/main/sae.py

wget  https://global.synologydownload.com/download/Package/spk/NVIDIARuntimeLibrary/1.0.2-0103/NVIDIARuntimeLibrary-dva3221-1.0.2-0103.spk

python3 sae.py  -k SPK -a NVIDIARuntimeLibrary-dva3221-1.0.2-0103.spk -d ./nvidiadriver

**Comment by jan-oratowski** [comment]
@lephino did you manage to make it work? I have the same problem with DS1515+ firmware, however it seems that it works fine for other people.

**Comment by jan-oratowski** [comment]
@lephino @K4L0dev 

I have solved it - turns out you have to run the command as root or with sudo.
