### ISSUE TITLE
Works with nano pat files but not system pat files

### ISSUE THREAD

**Issue by 007revad** [K4L0dev/Synology_Archive_Extractor#3]
I'm running sae.py with python 3.8.15 on a DS1821+ with DSM 7.2-64570 Update 3

For me this works perfectly on nano .pat files.

But I can't get it to work on full system .pat files. 
- The first time I tried, months ago in 7.2-u1, was getting `Failed to open SynoArchive(errno: 23)`
- Today in 7.2-u3 I'm getting `Failed to open SynoArchive(errno: 14)`

Do you know why it won't work for me for full system .pat files?

Also, could you include the errorcode like `Failed to open SynoArchive (errno: 14: Bad address)`

**Comment by 007revad** [comment]
After testing some other system pat files I've found it is only this .pat file causing an issue: 
https://global.synologydownload.com/download/VS600HD/release/1.0.1/33/VS600HD_0033.pat

**Comment by K4L0dev** [comment]
This is not a DSM system. I think it has a different synoarchive decryption key.
Do you have a backup of a working VS binary?

**Comment by K4L0dev** [comment]
SynoArchiveErrortype:
    OK = 0,
    ERR_OPEN_ARCHIVE_FAILED = 1,
    ERR_READ_VERSION = 2,
    ERR_READ_HEADER_LEN = 3,
    ERR_READ_HEADER = 4,
    ERR_SODIUM_INIT_FAILED = 5,
    ERR_INVALID_FORMAT = 6,
    ERR_INVALID_VERSION = 7,
    ERR_INVALID_HEADER = 8,
    ERR_INVALID_HEADER_MSGUNPACK = 9,
    ERR_INVALID_HEADER_OBJECT_TYPE = 10,
    ERR_INVALID_HEADER_UUID_TYPE = 11,
    ERR_INVALID_HEADER_UUID_SIZE = 12,
    ERR_CREATE_ENTRY_KEY = 13,
    ERR_INVALID_SIGNATURE = 14,
    ERR_READ_NEW_FAILED = 15,
    ERR_WRITE_DISK_NEW_FAILED = 16,
    ERR_FILEPATH = 17,
    ERR_FILE_NOT_FOUND = 18,
    ERR_HEADER_EXCEED_MAX = 19,
    ERR_UNKNOWN_KEY_TYPE = 20,
    ERR_EXPIRED = 21,
    ERR_SERIALNUM_MISMATCH = 22,
    ERR_OPEN_FILE = 23
